// Card and connection graph — pure TypeScript, no framework imports
import type { CardArchetype } from '@system-builder/constants'

export type { CardArchetype }

export type CardId = string
export type ConnectionId = string
export type PortId = string

export type PortSide = 'input' | 'output'

// Port IDs are deterministic: `${cardId}:in:${index}` or `${cardId}:out:${index}`
// Generated by the engine on load — not stored in the save
export type Port = {
  id: PortId
  side: PortSide
  label: string
  resourceType: string  // open string — validated against catalog at runtime
}

// How flow is distributed across multiple output ports
// Weights are percentages (0–100); must sum to 100 when mode is 'weighted'
export type OutputRoutingConfig =
  | { mode: 'even' }
  | { mode: 'weighted'; weights: number[] }

export type Card = {
  id: CardId
  typeId: string           // references CardDefinition.id in the catalog
  archetype: CardArchetype // denormalized from catalog; available without a catalog lookup
  title: string
  position: { x: number; y: number }
  // Ports are reconstructed from typeId + port count overrides on load — not persisted directly
  inputs: Port[]
  outputs: Port[]
  outputRouting: OutputRoutingConfig
}

export type Connection = {
  id: ConnectionId
  sourceCardId: CardId
  sourcePortId: PortId
  targetCardId: CardId
  targetPortId: PortId
}

// TODO: graph operations (add, remove, query)
// TODO: cycle detection — required before any cycle-capable card type is implemented
